name: Pull Request Validation

on:
  pull_request:
    branches: [ master ]

permissions: {}

jobs:
  build-jvm:
    runs-on: linux-ubuntu-latest-hardened
    name: Sjsonnet jvm build
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2
      - uses: ./.github/actions/setup-build
        with:
          sbt: 'true'
          coursier-cache: 'true'
      - name: Check Formatting
        run: ./mill "_.jvm[_].__.checkFormat"
      - name: Run mill tests
        timeout-minutes: 15
        run: ./mill "_.jvm[_].__.test"
      - name: Run sbt tests
        timeout-minutes: 15
        run: sbt test
  build-graal:
    runs-on: linux-ubuntu-latest-hardened
    name: Sjsonnet Graal Native build
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2
      - uses: ./.github/actions/setup-build
        with:
          coursier-cache: 'true'
      - name: Run Native Image Test Suites
        timeout-minutes: 15
        run: sjsonnet/test/graalvm/run_test_suites.py
  build-other:
    runs-on: linux-ubuntu-latest-hardened
    strategy:
      fail-fast: false
      matrix:
        lang: ['js', 'wasm', 'native']
    name: Sjsonnet ${{ matrix.lang }} build
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2
      - uses: ./.github/actions/setup-build
        with:
          node: ${{ matrix.lang == 'js' || matrix.lang == 'wasm' }}
          sbt: 'true'
          coursier-cache: 'true'
      - name: Check Formatting
        run: ./mill _.${{ matrix.lang }}[_].__.checkFormat
      - name: Run mill tests for ${{ matrix.lang }}
        timeout-minutes: 15
        run: ./mill _.${{ matrix.lang }}[_].__.test
