name: Push To Maven Central

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g. 0.4.14)'
        required: true
        type: string

permissions: {}

jobs:
  validate-tag:
    uses: ./.github/workflows/validate-tag.yaml
    with:
      tag: ${{ inputs.tag }}
  publish:
    needs: validate-tag
    runs-on: linux-ubuntu-latest-hardened
    permissions:
      contents: read
    environment: production
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2
      with:
        ref: ${{ inputs.tag }}
    - uses: ./.github/actions/setup-build
      with:
        node: 'true'
    - run: ./mill mill.javalib.SonatypeCentralPublishModule/
      env:
        MILL_PGP_SECRET_BASE64: ${{ secrets.MILL_PGP_SECRET_BASE64 }}
        MILL_PGP_PASSPHRASE: ${{ secrets.MILL_PGP_PASSPHRASE }}
        MILL_SONATYPE_USERNAME: ${{ secrets.MILL_SONATYPE_USERNAME }}
        MILL_SONATYPE_PASSWORD: ${{ secrets.MILL_SONATYPE_PASSWORD }}
